# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {c:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/FullAdder.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/DFlipFlop.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/DFlipFlop_NEW.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/decode.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/comp.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/Adder.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/MUX_NEW1.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/Register.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/MUX.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/imports/new/MUX4to1.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/immediate_generator.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/Instmem.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/CU.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/ALUContol.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/MUXarr.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/DataMem.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/RegisterFile.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/ALU.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/thirtytwoshiftleft.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/Registernew.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/Addernew.v}
  {C:/Users/Sabouzeid0/Desktop/Milestone 3/Milestone 2/Project 1 - Milestone 2/Project 1 - Milestone 2.srcs/sources_1/imports/sources_1/new/RISC-V.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top RISCV -part xc7k70tfbv676-1


write_checkpoint -force -noxdef RISCV.dcp

catch { report_utilization -file RISCV_utilization_synth.rpt -pb RISCV_utilization_synth.pb }
